name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]  # Adjust Node.js versions as needed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run Playwright tests
      run: npx playwright test

    - name: Upload Playwright test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: playwright-results
        path: playwright-report
