name: CI/CD for Unit Testing, Eslint Check and E2E Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Install Playwright browsers
      run: npx playwright install

    - name: Run ESLint
      run: npx eslint 'src/**/*.{js,jsx,ts,tsx}'

    - name: Run Jest tests
      run: npm test -- --coverage

    - name: Upload Jest coverage report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage/lcov-report
        retention-days: 5

    - name: Run Playwright tests
      run: npx playwright test

    - name: Upload Playwright test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-results
        path: playwright-report
        retention-days: 5
