name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Updated to v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4  # Updated to v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run Playwright tests
      run: npx playwright test --reporter=list

    - name: Upload Playwright test results
      if: always()
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: playwright-results
        path: playwright-report
